name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # récupère le thème Ananke

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.150.0'
          extended: true  # Hugo Extended nécessaire pour SCSS

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}  # ou GITHUB_TOKEN si dépôt à ton compte
          publish_dir: ./public
          publish_branch: gh-pages
